#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    todo-web-80-http:
      entrypoints:
        - http-33000
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "todo-redirectHttps"
    todo-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "todo-redirectHttps"
    todo-web-5173-http:
      entrypoints:
        - http-5172
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-web-5173"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "todo-redirectHttps"
    todo-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "todo-redirectHttps"
    
    
    
    
    todo-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-web-80"
      ruleSyntax: v3
      
      tls: true
      
    todo-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    todo-web-5173-https:
      entrypoints:
        - http-5173
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-web-5173"
      ruleSyntax: v3
      
      tls: true
      
    
    todo-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^todo\.ddev\.site$`)
      
      service: "todo-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    todo-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    todo-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-todo-web:80
        
    todo-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-todo-web:8025
        
    todo-web-5173:
      loadbalancer:
        servers:
          - url: http://ddev-todo-web:5173
        
    
    
    
    todo-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-todo-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/todo.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/todo.key